name: piemail_sogo

services:

  # Net Services
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - sogo
    profiles: [cloudflared]
    networks:
      - exit
      - internal

  # Core Services
  sogo:
    image: pmietlicki/sogo:latest
    restart: unless-stopped
    environment:
      memcached: ${memcached:-64}
    volumes:
      - sogo_config:/srv
    depends_on:
      db:
        condition: service_healthy
    networks:
      - exit
      - internal

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?DATABASE_PASSWORD environment variable is required}
      POSTGRES_USER: ${DATABASE_USER:-sogo}
      PGUSER: ${DATABASE_USER:-sogo}
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${DATABASE_USER:-sogo}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - internal

volumes:
  sogo_config:
    name: ${COMPOSE_PROJECT_NAME}_CONFIG_VOL
    labels:
      com.example.description: "(SOGo) Config volume"
  db_data:
    name: ${COMPOSE_PROJECT_NAME}_DB_DATA_VOL
    labels:
      com.example.description: "(SOGo) Database volume"

networks:
  exit:
    name: ${COMPOSE_PROJECT_NAME}_EXIT_NET
    attachable: false
    driver: bridge
  internal:
    name: ${COMPOSE_PROJECT_NAME}_INTERNAL_NET
    attachable: false
    internal: true